name:  Bug Report
description: Reportar un error o comportamiento inesperado
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Gracias por tomarte el tiempo de reportar este bug. Por favor, completa la siguiente informaci贸n.

  - type: textarea
    id: description
    attributes:
      label: Descripci贸n del bug
      description: Una descripci贸n clara y concisa del bug
      placeholder: Cu茅ntanos qu茅 sali贸 mal...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Pasos para reproducir
      description: Pasos para reproducir el comportamiento
      placeholder: |
        1. Ir a '...'
        2. Hacer click en '...'
        3. Scrollear hasta '...'
        4. Ver error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Comportamiento esperado
      description: Qu茅 esperabas que sucediera
      placeholder: Deber铆a...
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Si aplica, a帽ade screenshots para explicar el problema
      placeholder: Arrastra y suelta im谩genes aqu铆

  - type: dropdown
    id: browser
    attributes:
      label: Navegador
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Otro
    validations:
      required: true

  - type: input
    id: device
    attributes:
      label: Dispositivo
      placeholder: ej. iPhone 12, MacBook Pro, Samsung Galaxy S21
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Contexto adicional
      description: Cualquier otra informaci贸n relevante sobre el problema
